version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '5000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
      - ./todo_list_website:/var/www/website
  phpfpm:
    container_name: phpfpm
    build:
      context: .
      dockerfile: php_dockerfile.conf
    volumes:
      - ./todo_list_website:/var/www/website
  db:
    container_name: mysql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "todo_list"
    volumes:
      - practice-db:/var/lib/mysql
      - ./todo_list_website/database/todo_list.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  practice-db:
