version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
      - ./todo_list_website:/var/www/website
  phpfpm:
    container_name: phpfpm
    build:
      context: .
      dockerfile: php_dockerfile.conf
    volumes:
      - ./todo_list_website:/var/www/website
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: mysql_dockerfile.conf
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - practice-db:/var/lib/mysql
volumes:
  practice-db:
